# Generated by Django 3.0 on 2022-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-sellByUTC', '-isActive']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['fullName']},
        ),
        migrations.AlterField(
            model_name='token',
            name='sellByUTC',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
