# Generated by Django 3.0 on 2022-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220530_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtydata',
            old_name='obj',
            new_name='realty',
        ),
        migrations.AddField(
            model_name='realty',
            name='typeRealty',
            field=models.CharField(default='flat', max_length=20),
        ),
    ]
