# Generated by Django 3.0 on 2022-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220603_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='typeRealty',
            field=models.CharField(default='Квартира', max_length=20),
        ),
    ]
