# Generated by Django 3.0 on 2022-06-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220604_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
    ]
